# Base image
FROM python
FROM pytorch/pytorch:2.7.1-cuda11.8-cudnn9-runtime

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# ตั้ง working directory
WORKDIR /app

# copy dependency
COPY requirements.txt .

# install dependency
RUN pip install --no-cache-dir -r requirements.txt

# copy source code
COPY . .

# เปิด port
EXPOSE 5000

# run app
CMD ["python", "yolo_realtime.py"]
